const express = require("express");
const appRouter = require("./router/app_router");
const mongoose = require("mongoose");
require("dotenv").config();
const mongoose_connection = require("./db/connection");
const PORT = process.env.PORT | 3000;
const app = express();
mongoose_connection();
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(appRouter);
